name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      run: npm install && npx gatsby build
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
